version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.22
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: sqlite3
    versions:
    - 5.0.1
  - dependency-name: wait-on
    versions:
    - 5.2.1
  - dependency-name: "@fullcalendar/daygrid"
    versions:
    - 5.5.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
